### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by vergecurrency** [jaredallard/skype-to-irc#1]
so i filled in the config.. and go to start it up.. i see it come into the freenode channel i set in irc.js. then it tries to log into Skype, and doesn't succeed. 

``` js
dev@verge:~/skype/src# nodejs index.js
verge.relay correctskypepassword
GET  https://web.skype.com/ ...
SkypeWeb adapter failed to login!
phantom stderr: PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/63b3a4e6-120d-7e6d-484ad5c7-424072d7.dmp


assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: signal killed phantomjs: SIGSEGV
    at Console.assert (console.js:106:23)
    at ChildProcess.<anonymous> (/dev/skype/node_modules/phantom/phantom.js:152:21)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
```

**Comment by jaredallard** [comment]
This could be due to many things; 
1: PhantomJS API changed.
2: This is super old and unmaintained as I don't use IRC anymore.

But as I like to help out, what OS are you on? I'll see if I can migrate this (really bad code :()

**Comment by vergecurrency** [comment]
ah, saw it was from 7 months ago, figured it would still work out of the box. ill see what i can do and make a pr if im successful

**Comment by jaredallard** [comment]
@vergecurrency Hey, I'm actually re-writing this. I need one again, _so_ expect good things.

**Comment by jaredallard** [comment]
@vergecurrency Anddd it's _somewhat_ stable, I'll be ironing it out.
